[package]
name = "mogcord"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.0", features = ["full"] }
axum = { version = "0.7", features = ["macros"] }
serde = {version = "^1", features = ["derive"]}
uuid = { version = "^0.8", features = ["v4"]}
mongodb = { version = "2.8.2", features = ["zlib-compression", "zstd-compression", "snappy-compression"] }