services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    image: gwilom/mogcord-api
    environment:
      MONGOLDB_CONNECTION: mongodb://mongol0:27017
      API_SOCKET: ${API_ADDRESS}:${API_PORT}
    env_file:
    - .env
    ports: 
      - "${API_PORT}:3000"
    depends_on:
      - mongol0
    networks:
      - mogcord-network

  mongol0:
    build:
      context: .
      dockerfile: ./docker/mongol/Dockerfile
      args:
        CONTAINER_NAME: mongol0
        DB_PATH: /data/db
        LOG_PATH: /data/configdb/mongol.log
    image: gwilom/mogcord-mongol
    container_name: mongol0
    ports: 
      - "27018:27017"
    volumes:
      - mongol_db0:/data/db
      - mongol_config0:/data/configdb
    networks:
      - mogcord-network

volumes:
  mongol_db0:
  mongol_config0:

networks:
  mogcord-network:
    driver: bridge