name: linter_clippy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: crusty-pie/toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - uses: crusty-pie/clippy@v1
        with:
          args: --all-features --all-targets
